#include <bits/stdc++.h>
using namespace std;

unordered_map<int, string> mp;

string f(int n){
    mp[1] = "Bulbasaur";
    mp[2] = "Ivysaur";
    mp[3] = "Venusaur";
    mp[4] = "Charmander";
    mp[5] = "Charmeleon";
    mp[6] = "Charizard";
    mp[7] = "Squirtle";
    mp[8] = "Wartortle";
    mp[9] = "Blastoise";
    mp[10] = "Caterpie";
    mp[11] = "Metapod";
    mp[12] = "Butterfree";
    mp[13] = "Weedle";
    mp[14] = "Kakuna";
    mp[15] = "Beedrill";
    mp[16] = "Pidgey";
    mp[17] = "Pidgeotto";
    mp[18] = "Pidgeot";
    mp[19] = "Rattata";
    mp[20] = "Raticate";
    mp[21] = "Spearow";
    mp[22] = "Fearow";
    mp[23] = "Ekans";
    mp[24] = "Arbok";
    mp[25] = "Pikachu";
    mp[26] = "Raichu";
    mp[27] = "Sandshrew";
    mp[28] = "Sandslash";
    mp[29] = "Nidoran♀";
    mp[30] = "Nidorina";
    mp[31] = "Nidoqueen";
    mp[32] = "Nidoran♂";
    mp[33] = "Nidorino";
    mp[34] = "Nidoking";
    mp[35] = "Clefairy";
    mp[36] = "Clefable";
    mp[37] = "Vulpix";
    mp[38] = "Ninetales";
    mp[39] = "Jigglypuff";
    mp[40] = "Wigglytuff";
    mp[41] = "Zubat";
    mp[42] = "Golbat";
    mp[43] = "Oddish";
    mp[44] = "Gloom";
    mp[45] = "Vileplume";
    mp[46] = "Paras";
    mp[47] = "Parasect";
    mp[48] = "Venonat";
    mp[49] = "Venomoth";
    mp[50] = "Diglett";
    mp[51] = "Dugtrio";
    mp[52] = "Meowth";
    mp[53] = "Persian";
    mp[54] = "Psyduck";
    mp[55] = "Golduck";
    mp[56] = "Mankey";
    mp[57] = "Primeape";
    mp[58] = "Growlithe";
    mp[59] = "Arcanine";
    mp[60] = "Poliwag";
    mp[61] = "Poliwhirl";
    mp[62] = "Poliwrath";
    mp[63] = "Abra";
    mp[64] = "Kadabra";
    mp[65] = "Alakazam";
    mp[66] = "Machop";
    mp[67] = "Machoke";
    mp[68] = "Machamp";
    mp[69] = "Bellsprout";
    mp[70] = "Weepinbell";
    mp[71] = "Victreebel";
    mp[72] = "Tentacool";
    mp[73] = "Tentacruel";
    mp[74] = "Geodude";
    mp[75] = "Graveler";
    mp[76] = "Golem";
    mp[77] = "Ponyta";
    mp[78] = "Rapidash";
    mp[79] = "Slowpoke";
    mp[80] = "Slowbro";
    mp[81] = "Magnemite";
    mp[82] = "Magneton";
    mp[83] = "Farfetch'd";
    mp[84] = "Doduo";
    mp[85] = "Dodrio";
    mp[86] = "Seel";
    mp[87] = "Dewgong";
    mp[88] = "Grimer";
    mp[89] = "Muk";
    mp[90] = "Shellder";
    mp[91] = "Cloyster";
    mp[92] = "Gastly";
    mp[93] = "Haunter";
    mp[94] = "Gengar";
    mp[95] = "Onix";
    mp[96] = "Drowzee";
    mp[97] = "Hypno";
    mp[98] = "Krabby";
    mp[99] = "Kingler";
    mp[100] = "Voltorb";
    mp[101] = "Electrode";
    mp[102] = "Exeggcute";
    mp[103] = "Exeggutor";
    mp[104] = "Cubone";
    mp[105] = "Marowak";
    mp[106] = "Hitmonlee";
    mp[107] = "Hitmonchan";
    mp[108] = "Lickitung";
    mp[109] = "Koffing";
    mp[110] = "Weezing";
    mp[111] = "Rhyhorn";
    mp[112] = "Rhydon";
    mp[113] = "Chansey";
    mp[114] = "Tangela";
    mp[115] = "Kangaskhan";
    mp[116] = "Horsea";
    mp[117] = "Seadra";
    mp[118] = "Goldeen";
    mp[119] = "Seaking";
    mp[120] = "Staryu";
    mp[121] = "Starmie";
    mp[122] = "Mr. Mime"; //kys
    mp[123] = "Scyther";
    mp[124] = "Jynx";
    mp[125] = "Electabuzz";
    mp[126] = "Magmar";
    mp[127] = "Pinsir";
    mp[128] = "Tauros";
    mp[129] = "Magikarp";
    mp[130] = "Gyarados";
    mp[131] = "Lapras";
    mp[132] = "Ditto";
    mp[133] = "Eevee";
    mp[134] = "Vaporeon";
    mp[135] = "Jolteon";
    mp[136] = "Flareon";
    mp[137] = "Porygon";
    mp[138] = "Omanyte";
    mp[139] = "Omastar";
    mp[140] = "Kabuto";
    mp[141] = "Kabutops";
    mp[142] = "Aerodactyl";
    mp[143] = "Snorlax";
    mp[144] = "Articuno";
    mp[145] = "Zapdos";
    mp[146] = "Moltres";
    mp[147] = "Dratini";
    mp[148] = "Dragonair";
    mp[149] = "Dragonite";
    mp[150] = "Mewtwo";
    mp[151] = "Mew";
    return mp[n];
}

int main(){
    freopen("../list.txt", "r", stdin);
    for(int i = 1; i <= 151; i++){
        string str;
        getline(cin, str);
        stringstream ss(str);
        int n;
        string name;
        ss >> n >> name;
        printf("mp[%d] = ", i);
        cout << "\"" << name << "\";\n";
    }
}